### PR TITLE
added smart sleep before reading, just like when writing

### PR DESCRIPTION
**Pull request by hariseldon78**
hi. we had some issues while reading from eeprom, so we added in the read function the same "sleep and poke" mechanics that you used in the write. Now it works very well, please merge if you like it.

### CODE REVIEW

**Comment by JChristensen** [comment]
Hi, this is interesting, I hadn't encountered such a problem before. I'd like to try and recreate it. Which EEPROMs were used? Also, if there is a short example demonstrating the issue, I'd be interested in seeing it.
PS: Also an Asimov fan.

**Comment by hariseldon78** [comment]
hello. i'm sorry i don't have much time to reproduce the issue, anyway this
is the model of the eeprom we used:
http://rover.ebay.com/rover/0/e11401.m1842.l3160/7?euid=3f3c926c68cf43edb49bb3f6d8e77055&loc=http%3A%2F%2Fcgi.ebay.it%2Fws%2FeBayISAPI.dll%3FViewItem%26item%3D221490657932%26ssPageName%3DADME%3AL%3AOU%3AIT%3A3160&exe=10061&ext=100153&sojTags=exe=exe,ext=ext

## it's really cheap and probably slow..

roby

Il giorno dom 10 mag 2015 alle ore 12:41 Jack Christensen <
notifications@github.com> ha scritto:

**Comment by hariseldon78** [comment]
ps. asimov rocks!!!

Il giorno gio 28 mag 2015 alle ore 14:13 Roberto Previdi <
hariseldon78@gmail.com> ha scritto:

**Comment by JChristensen** [comment]
I had a look at the [datasheet on Atmel's site](http://www.atmel.com/Images/Atmel-8568-SEEPROM-AT24C256C-Datasheet.pdf) and this chip looks to be very similar if not identical to Microchip's 24AA256 which I've used without problems (as well as 24LC256, 24FC256).

I am strongly biased against parts from eBay; they could well be counterfeit, removed from scrapped equipment, etc. Unless I can observe the issue with a chip of known quality, I'm not inclined to make any changes. I'd be willing to buy a couple of the Atmel EEPROMs next time I order parts from Digi-Key or Mouser, but I'd still want [example code](http://www.sscce.org/) demonstrating the issue from you.

Therefore I'm closing this issue for now, pending example code.

**Comment by hariseldon78** [comment]
No problem, if and when i have time i will provide you with an example code, in the while people who have the problem i had can just search in the forks section...

**Pull request closed without merging**
